services:
  - type: web
    name: bill-generator-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    buildFilter:
      paths:
        - server/**
    healthCheckPath: /api/health 